Repository emc-mongoose/mongoose-storage-driver-kafka, pull requests merged in 2019-06, with the labels that each got.

#45 Fix create record test
  src/test/java/com/emc/mongoose/storage/driver/kafka/integration/CreateRecordTest.java
Labels: ready for review, reviewing

#47 Update README.md, add performance comparison
  README.md
Labels: ready to merge

#48 Added functional test
  ci/gitlab-ci.yaml
  src/test/robot/api/__init__.robot
  src/test/robot/api/storage/__init__.robot
  src/test/robot/api/storage/create_record.robot
Labels: ready for review

#39 Add basic implementation of batch read records mode
  src/main/java/com/emc/mongoose/storage/driver/kafka/KafkaStorageDriver.java
  src/main/java/com/emc/mongoose/storage/driver/kafka/cache/AdminClientCreateFunction.java
  src/main/java/com/emc/mongoose/storage/driver/kafka/cache/AdminClientCreateFunctionImpl.java
  src/main/java/com/emc/mongoose/storage/driver/kafka/cache/ConsumerCreateFunction.java
  src/main/java/com/emc/mongoose/storage/driver/kafka/cache/ConsumerCreateFunctionImpl.java
Labels: ready to merge
